### ISSUE TITLE
Add configuration options for backup files

### ISSUE THREAD

**Issue by nfarrar** [rcmdnk/homebrew-file#28]
When rerunning brew file init (when you already have a brew file, but things got out of sync) - homebrew-file creates the backup file 'brewfile.bak' in the same directory as the original file. It would be helpful to timestamp this file and allow a configurable path.

I keep my brewfile synchronized across several systems, because of this, the brewfile can get out of sync pretty easily. It would be very helpful to:

- change the save path for the brewfile backup (so I can have backups saved to `$XDG_CACHE_HOME/homebrew/*.bak`, rather than polluting my config directories
- have them timestamped, so that each backup doesn't overwrite the previous backup
- have them timestamped, so that i can easily reference the date they were relevant

Any possibility of adding this?

**Comment by rcmdnk** [comment]
I think the backup is no longer needed because it is normally managed in git repository or cloud storage in these a history is available.

Then, I implemented new option of `-b`, `--backup`, and environment variable `HOMEBREW_BREWFILE_BACKUP` to set the backup file name.
The default is empty. If it is empty, no backup file is made.

**Comment by nfarrar** [comment]
Thanks, I'll try it out!
