### ISSUE TITLE
[Feature] Support Brew Gem

### ISSUE THREAD

**Issue by Derimagia** [rcmdnk/homebrew-file#34]
Brew Gem, for managing Gems through Brew:
https://github.com/sportngin/brew-gem

Right now after installing a pip from brew-gem, it won't add to the Brewfile. When cleaning up, the gem will be removed from the system since it isn't in the Brewfile.

**Comment by rcmdnk** [comment]
This is also fixed at 3.7.9.

On the other hand, though it could be beyond this issue,
brew-gem uses gem names as is,
which sometime conflict with original formula in Homebrew (such `git`).
And there are no way to search for such brew-gem installed one.

I made [a pull request](https://github.com/sportngin/brew-gem/pull/21) for this issue.
Once it is fixed, I will separate a management of `brew-gem` packages like it is doing for `brew-pip`.

**Comment by rcmdnk** [comment]
FYI.

brew-gem was updated to put `gem-` prefix to the package name.
If you install `heroku` by brew-gem like:

    $ brew gem install heroku

then, you will have `gem-heroku` in `brew list`.

brew-file has been updated to check such name,
and will make a list of `gem`, like:

    gem heroku

in Brewfile, instead of `brew gem-heroku`.

With this update, you become to able to use such `brew file install` with such gem- packages.
