### ISSUE TITLE
unable to run clamav on mac os 10.10.5

### ISSUE THREAD

**Issue by Battant** [rcmdnk/homebrew-file#40]
Hello,

Because clamxav became comercial and close source, I try to install clamav using hambrew

When I run clamscan I get this :

clamscan 
LibClamAV Error: cli_loaddbdir(): No supported database files found in /usr/local/Cellar/clamav/0.99.2/share/clamav
ERROR: Can't open file or directory

----------- SCAN SUMMARY -----------
Known viruses: 0
Engine version: 0.99.2
Scanned directories: 0
Scanned files: 0
Infected files: 0
Data scanned: 0.00 MB
Data read: 0.00 MB (ratio 0.00:1)
Time: 0.009 sec (0 m 0 s)
`

When I run freshclam I get this
`
sudo freshclam
ERROR: Can't open/parse the config file /usr/local/etc/clamav/freshclam.conf
``
Could you help me please to fix this issue ?

Thanks for your support

Battant

**Comment by rcmdnk** [comment]
Hello,

This repository is Homebrew-file, which is a management tool for Homebrew.
If you have a problem about such specific formula,
please try to make an issue at [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core), which manages these formulae.

Although I don't know about clamxav, but maybe it is because of commercialized, 
and formula is not updated.
