### ISSUE TITLE
Disable sportngin/brew-gem

### ISSUE THREAD

**Issue by giordanovi** [rcmdnk/homebrew-file#67]
How can i disable automatically install the sportngin/brew-gem package?
I need development gems and sportngin/brew-gem install the packages in a sandbox enviroment.

**Comment by rcmdnk** [comment]
brew-gem is installed at `init` command when you have `gem` inputs in your Brewfile,
or when you execute `brew gem ...` command with brew-wrap.
In these cases, brew-gem is needed in any case.

I'm not sure about your "sandbox" environment, but Homebrew is not made for sandbox, I think.
If you need gems in a sandbox environment, you can use normal `gem` command instead of `brew gem`.

**Comment by giordanovi** [comment]
If i execute `brew file update` brew-file wants to install `brew-gem` to handle `gem` inputs in my Brewfile. I don't want to install `brew-gem` because i need gems like `compass`, `sass` or `susy` that don't works with `brew-gem` installation system.

From brew-gem Philosophy:
`This is not for installing development libraries, but for standalone binary tools that you want system wide.`

**Comment by rcmdnk** [comment]
Then you should not have `gem` lines in Brewfile.
Homebrew and brew-file are for system wide installation.
Even if `gem` lines use `gem` command directly instead of brew-gem, gems will be installed system wide directory.
