### ISSUE TITLE
Method of syncing system to brew-file arguments of installed brew

### ISSUE THREAD

**Issue by derimagia** [rcmdnk/homebrew-file#72]
For example, if computer 1 has `gnu-which` installed and on another computer you do `brew install gnu-which --with-default-names`, when you sync the command back to the first it doesn't reinstall it with the "proper" flags.

Not that big of a deal but I have hit it a few times

**Comment by rcmdnk** [comment]
Thanks for the report.

I've updated brew-file to check options at `install` command, too.
If option is different, it does `brew reinstall` with new option.

**Comment by derimagia** [comment]
For me this seems to now be re-installing every app that has an arg in it everytime I run `brew file -F bundle -C -- update`. Any ideas?

**Comment by rcmdnk** [comment]
I confirmed that it happens when your Brewfile is normal (file) type,
and such different type (bundle) is used.
They have different option structure and they don't match, then brew-file try to re-install.

Currently, even if you made Brewfile with -F bundle option once,
if you does `update` w/o -F option then normal type Brewfile is created.

I will update to check file type when it is read.

For now, please initialize Brewfile again with `brew file init -F bundle`.
Then, you can do `brew file -F bundle -C -- update` w/o such annoying re-installation.

**Comment by rcmdnk** [comment]
ok, fixed.

You can use different type between input and `-F` option,
w/o unnecessary re-installation.

Now brew-file follows Brewfile's type.
Once you made Brewfile by such:

     $ brew file init -F bundle

then, you need to do just:

    $ brew file -C update

which will update Brewfile with bundle type.

**Comment by derimagia** [comment]
Thanks! Seems to work great. Automatically detecting the type of your brewfile is a handy feature as well.
