### ISSUE TITLE
Use new `installed_on_request` and `installed_as_dependency` flags

### ISSUE THREAD

**Issue by derimagia** [rcmdnk/homebrew-file#75]
Here's the commit that added it: https://github.com/Homebrew/brew/commit/b99fb562753b45e7efec13366b32ddd2f58194f9

Was curious if you were aware of it and if there was any thought of using it? (Maybe to replace leaves from #41) so that it only exports packages that you requested to install

**Comment by rcmdnk** [comment]
hmm interesting.
let me check how to use them and if we can use it or not.

**Comment by rcmdnk** [comment]
I've implemented `--on_request` option for `init` command,
which writes out only `installed_on_requst=True` packages.
This also can be enabled by environmental variable:

    export HOMEBREW_BREWFILE_ON_REQUEST=1

Note: Packages, which were installed before `installed_on_request` was implemented,
are set as `installed_on_request=None`,
so that brew-file writes out these packages anyway.

If you wish to clean up fully, you need to `reinstall` all packages as you like.

`clean_non_request` shows packages which were installed as dependency,
but related package has been removed.
`clean_non_request -C` will remove these packages.

Another problem may happen when you install all packages in new machine,
because Brewfile itself doesn't have on_request information.
Assume you have such package1 and package2,
and package1 requires package2,
but you want to install package2 on request.
In this case, if package1 is listed in the Brewfile first, package1 is installed first and package2 is installed as dependency.
It could be possible to use new Brewfile format like:

    brew vim --with-lua, installed_on_request

It needs to change some functions and may takes time, but I put it in todo list.

**Comment by derimagia** [comment]
This is working really well, the main issue I'm seeing is the order of the list keeps changing every once in a while. It also changes when you remove a package which is also a dependency for some other thing you use. 

The other one will jump up in the list. Here's an example: https://github.com/derimagia/dotfiles/commit/fc96131c3db681cc3109893c7c6c36d68667d38a

Thoughts? Maybe we should add them all and then filter the non-leaves out afterwards?

**Comment by rcmdnk** [comment]
ok, sort function is added before initializing Brewfile. (v4.3.0)

**Comment by derimagia** [comment]
Thanks, appreciate your fast response times
